name: pythonworkflow
on: workflow_dispatch

jobs:

  data_pipeline:
    name: data_pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ./ModelCleaning
    - name: clean_data
      run: |
        pwd
        ls -l
        cd ./ModelCleaning
        ls  -al
        pwd
        python cleandata.py